### ISSUE TITLE
Alan Brennan - some further suggestions to readme

### ISSUE THREAD

**Issue by alanbrennan1965** [ScHARR-PHEDS/DoPE_Public#5]
Hi @RobertASmith 
As a new reader i would welcome something in the readme that says:

**Summary of Code**
There are two R scripts used in running this analysis
Script1 is:  src1_data_proc.R
Purpose: 
Key features:
Outputs:

next the user runs
Script2 which is:  src1_data_proc.R
Purpose: 
Key features:  
Outputs:

**Comment by RobertASmith** [comment]
@alanbrennan1965 Thanks for this useful suggestion -  I have created a branch which addresses this issue: https://github.com/ScHARR-PHEDS/DoPE_Public/blob/RobertASmith-patch-1/README.md

**Comment by RobertASmith** [comment]
@alanbrennan1965  as you can see above I merged the branch that I made to address this issue.
